 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for defining logical data models in YAML, designed for RDB/Graph neutral representation.
 */
export interface LogicalDataModelIntermediateRepresentationSchema {
  /**
   * Version of this schema definition.
   */
  schema_version: "1.0";
  /**
   * Unique name for the data model (Alphanumeric and underscores).
   */
  model_name: string;
  /**
   * Description of the entire data model.
   */
  description?: string;
  /**
   * Collection of entities defined in the model.
   */
  entities: {
    [k: string]: Entity;
  };
  [k: string]: unknown;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[A-Z][a-zA-Z0-9]*$".
 */
export interface Entity {
  /**
   * Description of the entity, including source references.
   */
  description: string;
  attributes: {
    [k: string]: Attribute;
  };
  relationships?: {
    [k: string]: Relationship;
  };
  [k: string]: unknown;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-z][a-z0-9_]*$".
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-z][a-z0-9_]*$".
 */
export interface Attribute {
  /**
   * Data type of the attribute.
   */
  type:
    | "String"
    | "Integer"
    | "Float"
    | "Boolean"
    | "Date"
    | "DateTime"
    | "Text"
    | "Enum";
  /**
   * Business definition of the attribute.
   */
  description: string;
  required?: boolean;
  primary_key?: boolean;
  /**
   * Additional implementation notes or constraints.
   */
  note?: string;
  /**
   * List of allowed values if type is Enum.
   */
  options?: string[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-z][a-z0-9_]*$".
 */
export interface Relationship {
  /**
   * Name of the target entity (Must match an entity key).
   */
  target: string;
  /**
   * Description of the relationship context.
   */
  description?: string;
  /**
   * Cardinality from the source entity to the target entity.
   */
  cardinality: "1:1" | "1:N" | "0:1" | "0:N" | "N:M";
  /**
   * Properties/Attributes specifically for this relationship (edge properties).
   */
  attributes?: {
    [k: string]: Attribute;
  };
  [k: string]: unknown;
}
