import { parseArgs } from 'node:util';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { parse } from 'yaml';
import { PrismaSchemaBuilder } from './core/PrismaSchemaBuilder';
import { LogicalDataModelIntermediateRepresentationSchema } from './types/logical_model';

// Template for UserDefinedRelationship
// Depending on execution context (ts-node vs node dist), this might vary.
// For development with ts-node, src/templates is adjacent to src/index.ts.
const TEMPLATE_PATH = path.join(__dirname, 'templates', 'UserDefinedRelationship.prisma');

// Default paths
const DEFAULT_INPUT = 'logical_model.yaml';
const DEFAULT_OUTPUT = 'prisma/schema.prisma';

async function main() {
  const { values } = parseArgs({
    options: {
      input: {
        type: 'string',
        short: 'i',
        default: DEFAULT_INPUT,
      },
      output: {
        type: 'string',
        short: 'o',
        default: DEFAULT_OUTPUT,
      },
      'dry-run': {
        type: 'boolean',
        default: false,
      },
    },
  });

  const inputPath = path.resolve(process.cwd(), values.input as string);
  const outputPath = path.resolve(process.cwd(), values.output as string);
  const isDryRun = values['dry-run'];

  console.log(`Reading from: ${inputPath}`);

  if (!fs.existsSync(inputPath)) {
    console.error(`Error: Input file definition not found at ${inputPath}`);
    process.exit(1);
  }

  // 1. YAMLの読み込み
  const yamlContent = fs.readFileSync(inputPath, 'utf-8');
  let logicalModel: LogicalDataModelIntermediateRepresentationSchema;
  
  try {
    logicalModel = parse(yamlContent) as LogicalDataModelIntermediateRepresentationSchema;
  } catch (e) {
    console.error('Error parsing YAML:', e);
    process.exit(1);
  }

  // TODO: 必要に応じてAJV等でスキーマ検証を実行 (今回は最小実装のためスキップ)

  // 2. Prismaロジックの生成
  const builder = new PrismaSchemaBuilder();
  const prismaSchemaCore = builder.build(logicalModel);

  // 3. テンプレートの結合
  let templateContent = '';
  if (fs.existsSync(TEMPLATE_PATH)) {
    templateContent = fs.readFileSync(TEMPLATE_PATH, 'utf-8');
  } else {
    // distフォルダや異なる構成で実行されている場合のフォールバック
    // または警告を表示
    console.warn(`Template not found at ${TEMPLATE_PATH}. Skipping UserDefinedRelationship append.`);
  }
  
  // 結合

  const finalSchema = [
    '// This file is automatically generated. Do not edit directly.',
    `// Source: ${path.basename(inputPath)}`,
    '',
    'generator client {',
    '  provider = "prisma-client-js"',
    '}',
    '',
    'datasource db {',
    '  provider = "postgresql"',
    '}',
    '',
    prismaSchemaCore,
    '',
    '// --- User Defined System Models ---',
    templateContent
  ].join('\n');

  if (isDryRun) {
    console.log(finalSchema);
  } else {
    // Ensure directory exists
    const dirname = path.dirname(outputPath);
    if (!fs.existsSync(dirname)) {
        fs.mkdirSync(dirname, { recursive: true });
    }
    fs.writeFileSync(outputPath, finalSchema);
    console.log(`Schema generated at: ${outputPath}`);
  }
}

main().catch(e => {
  console.error(e);
  process.exit(1);
});
